### ISSUE TITLE
Theta testnet progress tracking

### ISSUE THREAD

**Issue by uditvira** [cosmos/gaia#1173]
## Summary

After running the [Vega-testnet](https://github.com/cosmos/vega-test) last November and December, we gathered requirements for the Theta testnet in preparation for the v7-theta release due towards the end of Q1 2022. This is a tracking issue to capture high level objectives and tasks associated with that theta testnet.

## Problem Definition

High level goals and objectives include:
* Launch early in January 2022 with v6.0.0 to give gaia team a stable testnet
* Write re-usable code to modify genesis and orchestrate testnet to make this process reusable for future deployments
* Upgrade to v7.0.0 RC with a simulated governance process in Q1 2022
* Mimic mainnet state as closely as possible
* Aim for similar upgrade time in both testnet and mainnet upgrades
    * Run simulations with `—trace`?
* Assess whether we can continue using the same testnet past the Theta upgrade and for future upgrades as well
* Improve testnet onboarding through better documentation and syncing mechanisms
* Issue rewards to testnet participants in the form of limited edition testnet tokens (validators participating in each upgrade receive tokens for that upgrade)
* Increase tooling around monitoring and alerting
* Provide testnet support in testing module integrations in Gaia and hook in to module readiness process

## Proposal

Our current plan is to:
- [x] Create a new validator on the mainnet (aka Hydrogen-val). This allows us to minimimally modify our own validator instead of commandeering an existing validator as we did in the last testnet to achieve liveness
- [x] Export state as a `genesis.json` file
- [x] Modify the genesis file such  that
    - [x] Hydrogen-val has over 66% power so we can produce blocks
    - [x] Add liquid tokens for two purposes
        - Delegations to 4 more validators. (5 total validators will provide more stability to the network)
        - Faucet
    - [x] Add reward tokens to be sent out to validators helping us during the testnet
        - 1000 x THETA
        - 1000 x RHO
        - 1000 x LAMBDA
        - 1000 x EPSILON
- [x] Run five total validators
- [x] Run two sentry nodes and provide RPC endpoints
- [x] Provide state sync snapshots on two different nodes
- [x] Run a block explorer like Big Dipper
- [x] Provide alerting to testnet coordinators using Simply VC panic
- [x] Set up a Grafana dashboard to inspect key testnet stats 
- [x] Set up Keplr integration (this [jsfiddle](https://jsfiddle.net/puz9e0tv/7/) is how we did it for vega)
- [x] Automate faucet (e.g., investigate [this discord faucet](https://github.com/c29r3/cosmos-discord-faucet)) 
- [x] Consider running relayer with IBC channels to other chains

## What's missing here?
We will need to add more clarity around communication plan during launch/upgrade and how to sunset the vega testnet gracefully. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by uditvira** [comment]
All of the tasks are completed here. Closing this issue. Further issues will be tracked in the [testnets repo](https://github.com/cosmos/testnets).
