### ISSUE TITLE
Create Upgrade Checklist Template

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1354]
## Summary

Wanted to start taking notes about what it should include here:

* testnet
  * communication prep & docs update
  * RC
  * run for a week
  * final release
* docs - prepare `update-docs` branch on these repos before upgrade:
  * https://github.com/cosmos/testnets
  * https://github.com/cosmos/mainnet
  * https://github.com/cosmos/gaia
    * joining mainnet
    * quickstart
    * README.md
    * changelog
      * Add CLI / REST api changes
* proposal
  * generate binaries in release
  * predict block height for target date
* communication
  * blogposts
    * testnet - target validators on Interchain Medium
    * mainnet - target wider audience on Cosmos Medium
  * twitter 
    * link to testnet upgrade blog - @ cosmohub
    * link to mainnet upgrade blog -  @ cosmos @ cosmoshub
    * upgrade countdown -  @ cosmos @ cosmoshub
    * upgrade success story -  @ cosmos @ cosmoshub
  * discord, telegram, slack
    * testnet upgrade info (discord only)
    * link to mainnet upgrade instructions (all channels)
  * validator email list
    * upgrade instructions + link to mainnet blog - one week before upgrade
* update [chain registry](https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json)

(this isn't the most sensical format but just wanted a place to start brain dumping the things we're currently doing so we don't leave them out of the eventual template)

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Not sure if this would go under communication or docs...

- [ ] Breaking REST api changes
- [ ] Breaking CLI api changes

**Comment by glnro** [comment]
For Docs

- [ ] Prepare upgrade-docs branch to merge post upgrade

**Comment by nooomski** [comment]
I've edited the original post to add more detail around comms and docs and add @glnro suggestions as well.

**Comment by mmulji-ic** [comment]
@okwme @glnro @nooomski - looks like we're still missing this as a template, if so can add.
