### ISSUE TITLE
Integrate Mauth module

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1421]

**Comment by faddat** [comment]
don't know what it is, but suspect Gaia's better off without it.

**Comment by yaruwangway** [comment]
Hi @faddat , it is interchain account auth part, we will move it into gaia as a gaia module. Mauth means "message auth".

**Comment by yaruwangway** [comment]
integration of Mauth module:
- [x] bump module version
- [x] complete the code, check todos in the ica module code
- [x] manual local test (write scripts to test)
- [x] test ibc through ica if need fees (given setup ibc as bypass msg)
- [ ] ~docs for ica, give several exmaples of how to use ica~
- [x] e2e for ica including register ica, test bank send through ica, test ibc through ica
