### ISSUE TITLE
Integrate Groups module updates

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1423]
#### Implementation
- [x] Integration into app.go

#### Testing
- [ ] Unit Tests
- [ ] E2E Tests
	- [ ] [User Flows](#User-Flows)
- [ ] Contract Tests
	- [ ] [REST](#REST-Endpoints)
	- [ ] [GRPC](#GRPC-Endpoints)
	- [ ] [CLI](#CLI)
- [ ] [Simulations](https://github.com/cosmos/hub-eng/tree/main/tools/testing/scripts/simulations/groups)

#### Docs
- [ ] [Link]() to SDK tutorial
- [x] [Link](https://docs.cosmos.network/v0.46/modules/group/#) to SDK API Docs
- [ ] Update on Gaia Module Page ( #1668 )

##### User Flows
- [ ] Scenario 1: Create a group with two or more members
  - Create a group of 3 people with the admin as a member
  - Add and remove a new member to the same group
- [ ] Scenario 2: Create decision policies for the group
  - Create a threshold decision policy requiring 1/3 of the group voting power to pass a proposal
  - Create a percentage decision policy requiring 50% of the group voting power to pass a proposal
- [ ] Scenario 3: Submit and pass proposal to send tokens from the group threshold decision policy account to a recipient
  - Fund the threshold policy account
  - Submit proposal
  - Vote proposal
- [ ] Scenario 4: Submit and fail to pass a proposal to send tokens from the percentage decision policy account to a recipient
  - Submit the proposal
  - Vote proposal
- [ ] Scenario 5: Update percentage decision policy to 60% (`0.6`)
- [ ] Scenario 6: Create a new group with the percentage decision account as the admin

##### REST Endpoints
- [ ] [group info by group id](https://docs.cosmos.network/v0.46/modules/group/05_client.html#groupinfo-2) `/cosmos/group/v1/group_info/{group_id}`
- [ ] [group policy info by policy address](https://docs.cosmos.network/v0.46/modules/group/05_client.html#grouppolicyinfo-2) `/cosmos/group/v1/group_policy_info/{address}`
- [ ] [group members by group id](https://docs.cosmos.network/v0.46/modules/group/05_client.html#groupmembers-2) `/cosmos/group/v1/group_members/{group_id}`
- [ ] [groups by admin address](https://docs.cosmos.network/v0.46/modules/group/05_client.html#groupsbyadmin-2) `/cosmos/group/v1/groups_by_admin/{admin}`
- [ ] [groups policies by group id](https://docs.cosmos.network/v0.46/modules/group/05_client.html#grouppoliciesbygroup-2) `/cosmos/group/v1/group_policies_by_group/{group_id}`
- [ ] [groups policies by admin address](https://docs.cosmos.network/v0.46/modules/group/05_client.html#grouppoliciesbyadmin-2) `/cosmos/group/v1/group_policies_by_admin/{admin}`
- [ ] [proposal by id](https://docs.cosmos.network/v0.46/modules/group/05_client.html#proposal-3) `/cosmos/group/v1/proposal/{proposal_id}`
- [ ] [proposal by group policy address](https://docs.cosmos.network/v0.46/modules/group/05_client.html#proposalsbygrouppolicy-2) `/cosmos/group/v1/proposals_by_group_policy/{address}`
- [ ] [proposal votes by voter address](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votebyproposalvoter-2) `/cosmos/group/v1/vote_by_proposal_voter/{proposal_id}/{voter}`
- [ ] [votes by proposal](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votesbyproposal-2) `/cosmos/group/v1/votes_by_proposal/{proposal_id}`
- [ ] [votes by voter address](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votesbyvoter-2) `/cosmos/group/v1/votes_by_voter/{voter}`

##### GRPC Endpoints
- [ ] [GroupInfo](https://docs.cosmos.network/v0.46/modules/group/05_client.html#groupinfo) `cosmos.group.v1.Query/GroupInfo`
- [ ] [GroupPolicyInfo](https://docs.cosmos.network/v0.46/modules/group/05_client.html#grouppolicyinfo) `ccosmos.group.v1.Query/GroupPolicyInfo`
- [ ] [GroupMembers](https://docs.cosmos.network/v0.46/modules/group/05_client.html#groupmembers) `cosmos.group.v1.Query/GroupMembers`
- [ ] [GroupsByAdmin](https://docs.cosmos.network/v0.46/modules/group/05_client.html#groupsbyadmin) `cosmos.group.v1.Query/GroupsByAdmin`
- [ ] [GroupsPoliciesByGroup](https://docs.cosmos.network/v0.46/modules/group/05_client.html#grouppoliciesbygroup) `cosmos.group.v1.Query/GroupPoliciesByGroup`
- [ ] [GroupsPoliciesByAdmin](https://docs.cosmos.network/v0.46/modules/group/05_client.html#grouppoliciesbyadmin) `cosmos.group.v1.Query/GroupPoliciesByAdmin`
- [ ] [Proposal](https://docs.cosmos.network/v0.46/modules/group/05_client.html#proposal-2) `cosmos.group.v1.Query/Proposal`
- [ ] [ProposalsByGroupPolicy](https://docs.cosmos.network/v0.46/modules/group/05_client.html#proposalsbygrouppolicy) `cosmos.group.v1.Query/ProposalsByGroupPolicy`
- [ ] [VoteByProposalVoter](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votebyproposalvoter) `cosmos.group.v1.Query/VoteByProposalVoter`
- [ ] [VotesByProposal](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votesbyproposal) `cosmos.group.v1.Query/VotesByProposal`
- [ ] [VotesByVoter](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votesbyvoter) `cosmos.group.v1.Query/VotesByVoter`

##### CLI
**Query**
```
gaiad query group --help
```
- [ ] [`group-info`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#group-info)
- [ ] [`group-policy-info`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#group-policy-info)
- [ ] [`group-by-admin`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#groups-by-admin)
- [ ] [`group-policies-by-group`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#group-policies-by-group)
- [ ] [`group-policies-by-admin`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#group-policies-by-admin)
- [ ] [`proposal`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#proposal)
- [ ] [`proposals-by-group-policy`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#proposals-by-group-policy)
- [ ] [`vote`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#vote)
- [ ] [`votes-by-proposal`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votes-by-proposal)
- [ ] [`votes-by-voter`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#votes-by-voter)

**Transaction**
```
gaiad tx group --help
```
- [ ] [`create-group`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#create-group)
- [ ] [`update-group-admin`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#update-group-admin)
- [ ] [`update-group-members`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#update-group-members)
- [ ] [`update-group-metadata`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#update-group-metadata)
- [ ] [`create-group-policy`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#create-group-policy)
- [ ] [`create-group-with-policy`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#create-group-with-policy)
- [ ] [`update-group-policy-admin`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#update-group-policy-admin)
- [ ] [`update-group-policy-metadata`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#update-group-policy-metadata)
- [ ] [`update-group-policy-decision-policy`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#update-group-policy-decision-policy)
- [ ] [`create-proposal`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#create-proposal)
- [ ] [`withdraw-proposal`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#withdraw-proposal)
- [ ] [`vote`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#vote-2)
- [ ] [`exec`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#exec)
- [ ] [`leave-group`](https://docs.cosmos.network/v0.46/modules/group/05_client.html#leave-group)

**Comment by mmulji-ic** [comment]
Module integrated by @okwme , e2e tests need to be added by @glnro .

**Comment by okwme** [comment]
for cross reference: https://github.com/cosmos/gaia/issues/1318
