### ISSUE TITLE
Integrate Gov module updates

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1424]
#### Implementation
- [x] Integration into app.go

#### Testing
- [ ] Unit Tests
- [ ] E2E Tests
	- [ ] [User Flows](#User-Flows)
- [ ] Contract Tests
	- [ ] [REST](#REST-Endpoints)
	- [ ] [GRPC](#GRPC-Endpoints)
	- [ ] [CLI](#CLI)
- [ ] [Simulations](https://github.com/cosmos/hub-eng/tree/main/tools/testing/scripts/simulations/gov)

#### Docs
- [ ] [Link]() to SDK tutorial
- [x] [Link](https://docs.cosmos.network/v0.46/modules/gov/07_client.html) to SDK API Docs
- [ ] Update on Gaia Module Page

##### User Flows
- [x] [Scenario 1](https://github.com/cosmos/gaia/blob/main/tests/e2e/e2e_test.go#L106): The community wants to reward an individual for work, so a Gov proposal is submitted and voted on to both fund the Gov account via the Community Pool and to send tokens from the Gov account to the recipient.
  - Submit & pass _legacy_ proposal to fund gov acocunt via community pool
    1. Submit proposal
    2. Deposit proposal
    3. Vote proposal
  - Submit & pass proposal to fund recipient account
    1. Submit proposal
    2. Deposit proposal
    3. Vote proposal

- [x] [Senario 2](https://github.com/cosmos/hub-eng/blob/main/tools/testing/scripts/simulations/gov/gov.sh#L18): The community wants to increase the number of participating validators, so it proposes a legacy param change proposal
  - Submit & pass _legacy_ param change proposal
    1. Submit proposal
    2. Deposit proposal
    3. Vote proposal

- [x] [Scenario 3](https://github.com/cosmos/gaia/blob/main/tests/e2e/e2e_test.go#L148): A new release of Gaia is ready, so the community submits a proposal to upgrade the chain
  - Submit & pass new gov proposal executing `MsgSoftwareUpgrade` message.
    1. Submit proposal
    2. Deposit proposal
    3. Vote proposal

- [x] [Scenario 4](https://github.com/cosmos/gaia/blob/main/tests/e2e/e2e_test.go#L189): The community decides to cancel a pending upgrade and submits a proposal to cancel the upgrade
  - Submit & pass new gov proposal executing `MsgSoftwareUpgrade` message.
    1. Submit proposal
    2. Deposit proposal
    3. Vote proposal
  - Submit & pass new gov proposal executing `MsgCancelUpgrade` message.
    1. Submit proposal
    2. Deposit proposal
    3. Vote proposal

##### REST Endpoints
- [ ] [proposal by id](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposal-3) `/cosmos/gov/v1beta1/proposals/{proposal_id}`
- [ ] [all proposals](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposals-3) `/cosmos/gov/v1beta1/proposals`
- [ ] [proposal vote by voter](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#voter-vote) `/cosmos/gov/v1beta1/proposals/{proposal_id}/votes/{voter}`
- [ ] [all votes by proposal ](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#votes-3) `/cosmos/gov/v1beta1/proposals/{proposal_id}/votes`
- [ ] [module param by param](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#params-3) `/cosmos/gov/v1beta1/params/{params_type}`
- [ ] [proposal deposits by depositor](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#deposits-3) `/cosmos/gov/v1beta1/proposals/{proposal_id}/deposits/{depositor}`
- [ ] [all proposal deposits](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposal-deposits) `/cosmos/gov/v1beta1/proposals/{proposal_id}/deposits`
- [ ] [proposal tally](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#tally-2) `/cosmos/gov/v1beta1/proposals/{proposal_id}/tally`

##### GRPC Endpoints
- [ ] [proposal by id](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposal-2) `cosmos.gov.v1beta1.Query/Proposal`
- [ ] [all proposals](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposals-2) `cosmos.gov.v1beta1.Query/Proposals`
- [ ] [proposal vote by voter](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#vote-3) `cosmos.gov.v1beta1.Query/Vote`
- [ ] [all votes by proposal ](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#votes-2) `cosmos.gov.v1beta1.Query/Votes`
- [ ] [module param by param](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#params-2) `cosmos.gov.v1beta1.Query/Params`
- [ ] [proposal deposits by depositor](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#deposit-3) `cosmos.gov.v1beta1.Query/Deposit`
- [ ] [all proposal deposits](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#deposits-2) `cosmos.gov.v1beta1.Query/Deposits`
- [ ] [proposal tally](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#tallyresult) `cosmos.gov.v1beta1.Query/Deposits`

##### CLI
**Query**
```
gaiad query gov --help
```
- [ ] [`deposit`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#deposit)
- [ ] [`deposits`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#deposits)
- [ ] [`param`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#param)
- [ ] [`params`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#params)
- [ ] [`proposal`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposal)
- [ ] [`propsoals`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposals)
- [ ] [`proposer`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#proposer)
- [ ] [`tally`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#tally)
- [ ] [`vote`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#vote)
- [ ] [`votes`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#votes)

**Transaction**
```
gaiad tx gov --help
```
- [x] [`deposit`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#deposit-2)
- [ ] [`submit-legacy-proposal`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#submit-legacy-proposal)
  - [x] `community-pool-spend`
  - [ ] `ibc-upgrade`
  - [x] `param-change`
  - [ ] `update-client`
- [x] [`submit-proposal`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#submit-proposal)
  - [x] `/cosmos.upgrade.v1beta1.MsgSoftwareUpgrade`
  - [x] `/cosmos.upgrade.v1beta1.MsgCancelUpgrade`
  - [x] `/cosmos.bank.v1beta1.MsgSend`
- [x] [`vote`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#vote-2)
- [x] [`weighted-vote`](https://docs.cosmos.network/v0.46/modules/gov/07_client.html#weighted-vote)

**Comment by okwme** [comment]
can't this be closed since #1531 was merged @glnro ?
