### ISSUE TITLE
CheckList for rho release

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1535]
## Summary
contributors please add the issues for rho here for a final check before going to testnet and release.

Here is a check list for rho code (continuing updating):

- [ ] Rosetta API
    - [ ] add tests for rosetta api, and its data correctness.
    - [x] https://github.com/cosmos/gaia/issues/1529
    - [x] https://github.com/cosmos/gaia/issues/1618
    - [x] https://github.com/cosmos/gaia/issues/1518
- [ ] Global Fee Module
    - [x] docs for global fee (yaru)
    - [x] unit tests for global fee (yaru)
    - [x] add failure tests for global fee (yaru)
    - [x] add e2e test for setting up globalfee by gov proposal changing params and test the fee is valid (yaru)
    - [x] e2e test for bypass min fee (yaru)
    - [x] check fee not enough err log, should be `insufficient fee` rather than panic `panic: value method github.com/cosmos/cosmos-sdk/types.TxResponse.UnpackInterfaces called using nil *TxResponse pointer`  https://github.com/cosmos/gaia/issues/1534 (yaru)
    - [x] bypass min fee config order issue https://github.com/cosmos/gaia/issues/1486 
    - [x] check and test all the fee checks can bypass configured types of txs (yaru)
    - [ ] test ica from gov in e2e test
- [ ]  upgrade handler (Lauren)
- [x] Hermes
    - [x] confirm hermes config gas-price is working with global fee changes, [test results](https://github.com/cosmos/hub-eng/blob/4f6b6e77d2e5945f47fa9f3c56390c0bf6b12c22/tools/testing/scripts/simulations/globalfee/devnet_test_results.md)
- [ ] ICA module
    - [ ] docs for ica auth (Lauren)
    - [x] change whitelist of the ica host allowed msg types to blacklist of blocked msg types? https://github.com/cosmos/gaia/issues/1498    
    - [ ] add  `/ibc.applications.transfer.v1.MsgTransfer` to ica host allowed msg types. check if the whitelist of allowed smg types change to blacklist not allowed msg types.    
- [x] GOV module 
    - [x] clean up e2e test, comments, change govproposals fn not hardcoded. 
    - [x] refator s`submitLegacyProposalFundGovAccount` to `submitLegacyProposal`
- [x] Group module 
    - [x] Additional e2e test coverage for Groups module
- [ ] Packet Forwarding
    - [x] Packet forward middleware doesn't work [#1441](https://github.com/cosmos/gaia/issues/1441)
    - [x] add tests for packet-forward-middleware.
- [ ] Miscellaneous
    - [x] go version 1.18 (yaru)
    - [x] check `gaiad tendermint unsafe-reset-all` working
    - [x] Remove --mode validator flag" for the SDK [#1553](https://github.com/cosmos/gaia/issues/1553)
    - [x] check replace dependencies are replaced back to released version ibc, tm-db (yaru)    
    - [ ] refactor: rename all const.go alias.go or the other way rename all alias.go const.go
    - [x] Rho: clean gaia/app [#1557](https://github.com/cosmos/gaia/issues/1557)
    - [x] Tidy up imported packages orders [#1527](https://github.com/cosmos/gaia/issues/1527)
    - [x] make targets missing or fail [#1489](https://github.com/cosmos/gaia/issues/1489)
    - [x] `<!-- markdown-link-check-disable-next-line --> ` will generate an extra space, remove space
    - [x] contrib/scripts/protogen.sh ->  proto/scripts/protogen_globalfee.sh
    - [ ] add e2e test for [minor versions compatibility test](https://github.com/cosmos/gaia/issues/1318) (optional for rho major release)
    - [ ] test security issues
    - [x] rename NewBypassMinFeeDecorator to `FeeDecorator`
    - [x] [update third_party proto dependencies to use buf registry](https://github.com/cosmos/gaia/pull/1766)

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
@yaruwangway Could you please asses the relevance of this issue given that the scope of the Rho release was changed?

**Comment by yaruwangway** [comment]
Hi, this can be closed, I will just open an issue about rosetta api
