### ISSUE TITLE
v7.0.4 items to include

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1669]
* [ ]  https://github.com/cosmos/gaia/pull/1695
  * "v3.0.2 for ibc and v0.45.8 for sdk and tendermint v0.34.21" -@faddat
* [ ]  https://github.com/cosmos/gaia/issues/1449
* [ ]  #1486 
  *  after doing a spike to determine the scope of the work
* [ ]  Test on live network for 24 hours (where are the other release checklists documented again @glnro?)
* [ ] Backport E2E tests (optional)

**Comment by mmulji-ic** [comment]
@okwme any opinion on whether or not we should backport the new E2E tests that are being written now .. if yes, which subset? Should be added to the stable release policy.

**Comment by yaruwangway** [comment]
extra test before release:
test app.toml `bypass-min-fee-msg` 
- decoding `bypass-min-fee-msg`  is only working when put before `[telemetry]` in `app.toml`
- when init a new node, check the  `bypass-min-fee-msg`  is before `[telemetry]`

**Comment by yaruwangway** [comment]
add [auto release](https://github.com/cosmos/gaia/blob/main/.github/workflows/release.yml) to v7.0.4
