### ISSUE TITLE
checklist for release v7.0.4

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1731]
## Summary

The following should be included in v7.0.4 release
- [x] https://github.com/cosmos/gaia/issues/1727
- [ ] https://github.com/cosmos/gaia/pull/1728
- [ ] bump sdk to v0.45.8

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
close here, please check https://github.com/cosmos/gaia/issues/1669
