### ISSUE TITLE
Add vulnerability checking for Gaia app and its dependencies

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1879]
## Summary

Introduce automated vulnerability checking into the build process, so that any vulnerabilities are proactively addressed as soon as possible.

## Type

This issue addresses code, test automation tech debt.

## Impact

Application and library vulnerabilities will seep into the codebase and will not get addressed in a structural and timely manner. Over time, that will increase the probability of a critical security failure in the mainnet.

## Proposed Solution

Add vulnerability checking starting with [govulcheck](pkg.go.dev/golang.org/x/vuln/cmd/govulncheck), to a build target, that is used for nightly builds, releases and as a hook to pre-merge for PR's to main or release branches. Add notification of failures on nightly builds to the team slack channel. 

The following sub-tasks should be completed:

- [x] Update build script so that app & dependency checks can be done, see #1927
- [x] Add checking to nightly builds, see #2440 
- [x] Add Slack notification of failures, see #2440 
- [ ] Update contribution guidelines, general software process and release procedures to reflect the additional step of checking and fixing vulnerabilities, see #2755
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?
