### ISSUE TITLE
v0.45 compatible Rho Meta Issue

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1909]
In order to improve chances of ICS launching on time we're considering using v0.45.x for the next upgrade Rho. This may or may not include ICS itself but nonetheless should decrease the work needed to integrate ICS. Since the Cosmos Hub is becoming a security critical chain (security as the primary product offering) we are also considering a much more conservative timeline to updating to the latest release of the Cosmos SDK. To follow this path the following work needs to be done:

- [x] Downgrade gaia to v0.45.x (@okwme https://github.com/cosmos/gaia/pull/1902)
  - [x]  downgrade dependencies (IBC, Liquidity, IBC-Packet-Forward Middleware, Tendermint)
  - [x] Remove ICA Mauth
  - [x] Remove Groups
  - [x] Downgrade Gov to old gov
  - [x] Remove Global Fee Antehandler
  - [x] Remove broken tests
- [x] Add Back Global fee Antehandler (@yaruwangway https://github.com/cosmos/gaia/pull/1918)
  - [x] Needs to be fixed
  - [x] Needs tests added back
- [x] Add back IBC Packet Forward Middleware tests (@okwme #1941 )
  - [x] Needs to confirm that IBC packet forward middleware has a working version compatible with IBC v3.x.x
- [x] Fix Fee Grant E2E tests (@yaruwangway https://github.com/cosmos/gaia/pull/1940)
- [x] Add back `TestGaiaApp_Export` (@okwme #1955)
- [x] Check what `GetStakingKeeper` was doing and why it's needed
- [x] Regenerate swagger files without mauth (@yaruwangway https://github.com/cosmos/gaia/pull/1933 )
- [x] Update proto dependencies to sdk0.45, change from using buf registry to copy third_party to our repo (@yaruwangway https://github.com/cosmos/gaia/pull/1933)
- [ ] ensure all docs are up to date with changes (@yaruwangway @glnro )
  - [ ] gov is not legacy proposal anymore
  - [x] no mauth module
  - [x] no groups module
- [x] Confirm why `initTendermintConfig` was needed in `cmd/gaiad/cmd/root.go`
- [x] Confirm vesting does not have `execCreatePermanentLockedAccount` or `execCreatePeriodicVestingAccount` (@okwme  )
- [x] Add back gov tests `GovSoftwareUpgrade` , `GovCancelSoftwareUpgrade`, (@glnro https://github.com/cosmos/gaia/pull/1951 )
- [x] Add back `TestQueryGlobalFeesInGenesis` test (@yaruwangway https://github.com/cosmos/gaia/pull/1918)
- [x] Add ICS to gaia (@glnro https://github.com/cosmos/gaia/pull/1938 )
- [x] Investigate the `app/helpers/test_helpers.go` `setup` function that used to pre-populate with an account and a validator. (@okwme #1955)
~- [ ]  Add Admin/Composer module to Gaia~

**Comment by yaruwangway** [comment]
add upgrade test, [i disabled it](https://github.com/cosmos/gaia/pull/1920) for now since the upgrade version is wrong and test failed.

**Comment by yaruwangway** [comment]
Hi, @okwme 
"regenerate swagger files without mauth" means keep present swagger files for mauth or no need swagger files for mauth

**Comment by okwme** [comment]
> add upgrade test, [i disabled it](https://github.com/cosmos/gaia/pull/1920) for now since the upgrade version is wrong and test failed.

re-enabled since we still need to perform an upgrade

**Comment by okwme** [comment]
> Hi, @okwme "regenerate swagger files without mauth" means keep present swagger files for mauth or no need swagger files for mauth

no need for mauth in this release. It would be a nice to have but not essential so being removed to ensure we support the ICS timeline.

**Comment by mpoke** [comment]
Closing in favor of https://github.com/cosmos/gaia/issues/2032 and https://github.com/cosmos/gaia/issues/2034
