### ISSUE TITLE
EPIC: Upgrade to v8.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2032]
## Cosmos Hub Upgrade Epic

# Rho / v8.0.0

Check mark each item if it has been completed and ready for the upgrade. If not added yet, create an issue for each item and mark complete once it has been done and integrated.

- [x]  Upgrade to SDK version ~~v0.45.11~~ v0.45.12
- [x]  Upgrade to IBC version v3.4.0
- [x]  Integrate [globalfee](https://github.com/cosmos/gaia/tree/main/x/globalfee) module
  - Added  [e2e](https://github.com/cosmos/gaia/blob/main/tests/e2e/e2e_globalfee_test.go) and [unit tests](https://github.com/cosmos/gaia/tree/main/x/globalfee/ante/antetest)
  
- [x]  [Update Gaia roadmap](https://github.com/cosmos/gaia/issues/2063)

- [x]  Testnet
  - [x]  Communication prep
  - [ ]  Docs:
    - [x]  https://github.com/cosmos/testnets
    - [ ]  `gaia/docs/hub-tutorials/join-testnet.md`
  - [x]  Release candidate
  - [x]  Create testnet proposal
  - [x]  Run testnet for one week
  - [x]  Final Release

- [ ]  Docs:
  - [x] #2039
  - [ ]  https://github.com/cosmos/gaia
    - [ ]  `gaia/docs/hub-tutorials/join-mainnet.md` see issue https://github.com/cosmos/gaia/issues/2064
    - [ ]  `gaia/docs/getting-started/quickstart.md`
    - [ ]  `README.md`
    - [ ]  `changelog.md`
      - [ ]  Breaking REST api changes
      - [ ]  Breaking CLI api changes
  - [ ]  https://github.com/cosmos/mainnet
  - [x] Update chain-registry repo See [PR](https://github.com/cosmos/chain-registry/pull/1411)

- [x]  Mainnet Proposal
  - [x]  Predict block height for target date
  - [x]  Create forum post
  - [x]  Submit on-chain proposal

- [ ]  Communication
  - [ ]  Blogposts - [interchain foundation account](https://medium.com/the-interchain-foundation/tagged/cosmos-hub)
    - [ ]  Testnet - target validators on Interchain Medium
    - [x]  [Mainnet - target wider audience on Cosmos Medium](https://medium.com/the-interchain-foundation/cosmos-hubs-rho-upgrade-is-coming-110fed68de8a)
  - [ ]  Twitter
    - [ ]  Link to testnet upgrade blog - @ cosmohub
    - [ ]  Link to mainnet upgrade blog - @ cosmos @ cosmoshub
    - [ ]  Upgrade countdown - @ cosmos @ cosmoshub
    - [ ]  Upgrade success story - @ cosmos @ cosmoshub
  - [x]  Discord, Telegram, Slack
    - [x]  Testnet upgrade info (discord only)
    - [x]  Link to mainnet upgrade instructions (all channels)
  - [ ]  Validator email list
    - [ ]  Upgrade instructions + link to mainnet blog - one week before upgrade
  - [x]  Update chain registry after upgrade [PR](https://github.com/cosmos/chain-registry/pull/1411)

**Comment by glnro** [comment]
#2045 Fulfills the testnet docs objectives
