### ISSUE TITLE
EPIC: Upgrade to v9.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2034]
## Cosmos Hub Upgrade Epic

# Lambda / v9.0.0

Check mark each item if it has been completed and ready for the upgrade. If not added yet, create an issue for each item and mark complete once it has been done and integrated.

- [x] Release v9.0.0
  - [x]  Integrate ICS provider 
  - [x] Integrate ICS tests
  - [x] Update interchain-security `v1.0.0` 
  - [x] Update cosmos-sdk `v0.45.13-ics`
  - [x] Update ibc-go `v4.0.2` 
  - [x] Update packet-forward-middleware `v4.0.4`

- [x]  Testnet
  - [ ]  Communication prep
  - [ ]  Docs:
    - [ ] [testnets](https://github.com/cosmos/testnets) updated with most recent rc
    - [ ] [join-testnet](https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/join-testnet.md)
  - [x] [Release candidate - rc7](https://github.com/cosmos/gaia/releases/tag/v9.0.0-rc7)
    - [x] Update Packet Forwarding Module to 4.0.4
    - [x] Update ICS v1.0.0-rc7
    - [x] Update Cosmos SDK to v0.45.13-ics
    - [x] Update Tendermint to InformalSystems v0.34.25
  - [ ]  Audit issues
    - [ ] ...
  - [x]  Run testnet for two week
  - [x]  Final Release

- [ ]  Docs:
    - [ ] [quickstart](https://github.com/cosmos/gaia/pull/2291)
    - [ ] [join-mainnet](https://github.com/cosmos/gaia/pull/2292)
    - [ ] [chain-registry.json](https://github.com/cosmos/chain-registry/pull/1597)
    - [x] [Migration Docs](https://github.com/cosmos/gaia/pull/2240)
    - [x]  [v9 Changelog](https://github.com/cosmos/gaia/blob/v9.0.0/CHANGELOG.md#v900---2023-02-21)
  - [ ] Update [cosmos mainnet repo]( https://github.com/cosmos/mainnet) and make decision about future

- [x]  Mainnet Proposal
  - [x]  Predict block height for target date [14470501](https://www.mintscan.io/cosmos/blocks/14470501)
  - [x]  Create [forum post](https://forum.cosmos.network/t/proposal-187-vote-on-chain-v9-lambda-upgrade-with-replicated-security/8766)
  - [x]  Submit [on-chain proposal](https://www.mintscan.io/cosmos/proposals/187)

- [ ]  Communication
  - [x]  Blogposts
    - [x]  Testnet - target validators on Interchain Medium
    - [x]  Mainnet - target wider audience on Cosmos Medium
  - [x]  Twitter
    - [x]  Link to testnet upgrade blog - @ cosmohub
    - [x]  Link to mainnet upgrade blog - @ cosmos @ cosmoshub
    - [x]  Upgrade countdown - @ cosmos @ cosmoshub
    - [x]  Upgrade success story - @ cosmos @ cosmoshub
  - [x]  Discord, Telegram, Slack
    - [x]  Testnet upgrade info (discord only)
    - [x]  Link to mainnet upgrade instructions (all channels)
  - [x]  Validator email list
    - [x]  Upgrade instructions + link to mainnet blog - one week before upgrade
  - [x]  [Update chain registry after upgrade to v9.0.0](https://github.com/cosmos/chain-registry/pull/1486)
  - [x] [Update chain registry after upgrade to v9.0.1](https://github.com/cosmos/chain-registry/pull/1597)
