### ISSUE TITLE
EPIC: Improve UX for devops

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2081]
The following issues should be resolved:

- [x] https://github.com/cosmos/gaia/issues/1592
- [x] https://github.com/cosmos/gaia/issues/1848
- [x] https://github.com/cosmos/gaia/issues/1722
