### ISSUE TITLE
Fee antehandler audit and refactor

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2090]
## Summary
Global Fee (or Global Min Fee) is a gaia module which was supplied by [TGrade](https://github.com/confio/tgrade/tree/main/x/globalfee) which defines a fee all transactions have to satisfy (except by-pass-msg).

Currently, Gaia has two fees setups: the `mininum_gas_price` in `config/app.toml` and a global fee (a list of coins) in param store. 

Gaia fee antehandler takes min_gas_price, Global fee into a [combined fee requirement](https://github.com/cosmos/gaia/blob/e665d82397ba693f4f74fbad74eed8a5b1e64c6e/x/globalfee/ante/fee_utils.go#L122). The combined fee:

- takes the higher fees betweenmin_gas_price and global fee if min_gas_price and global_fee have the same denom. Otherwise, take the global fee
- consider the global fee denom as required denom even if global fee is zero coin

Gaia fee antehandler also can bypass bypass-msg(all msgs are bypass msg types and [not exceed `MaxBypassMinFeeMsgGasUsage`](https://github.com/cosmos/gaia/blob/983a9fe4288d6e474aea7402afc640fcbc67e842/x/globalfee/ante/fee.go#L67)), but if bypass-msg still pays fees, gaia fee antehandler will also check the denoms of the fee.

## Proposed Solution

- Audit is needed for the [fee antehandler](https://github.com/cosmos/gaia/tree/main/x/globalfee/ante) @tac0turtle if sdk team can help ?
 (@mpoke please confirm this is still the case)

- Document bypass-msg  https://github.com/cosmos/gaia/issues/2089

- Refactor global fee module @mpoke 

- Provide relayer and validators guidance of fee setups

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Refactor global fee module:
- [ ] change global fee from allow zero coins to not allow zero coins
- [ ] in sdk 0.47, params store is deprecated, the global fee params need to migrate from params store to its own store. https://github.com/cosmos/cosmos-sdk/pull/14992
- [ ] from sdk 0.46, we can use buf to refer proto deps registry, rather than copy paste proto files to gaia. https://github.com/cosmos/gaia/tree/v8.0.0-rc/proto

**Comment by yaruwangway** [comment]
close, in favor of #2228
