### ISSUE TITLE
Gaia v8.0.2 checklist

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2217]
## Summary
The following issues will be fixed in Gaia v8.0.2
- [x] Fix gaiad build tags https://github.com/cosmos/gaia/issues/2017 (backport also to v7 ?)
- [ ] state sync docs update https://github.com/cosmos/gaia/pull/2209
- [ ] fix `gaiad export/init` to output to stdout ? https://github.com/cosmos/gaia/issues/2249, (api breaking, might not fit a patch release)

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
Closing as we'll not backport to v8
