### ISSUE TITLE
Test Gaia against different hardware platforms and operating systems

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#2258]
## Summary

Add CI testing for Gaia releases against different hardware platforms and operating systems.

## Problem Definition

Currently quality assurance of Gaia is done on a limited number of platforms. Prioritised based on [community downloads](https://hanadigital.github.io/grev/?user=cosmos&repo=gaia) and other sources, we should clearly specify which platforms are supported and tested and which are not.

Implementing these checks will highlight any platform/performance issues earlier before releases are made and not in the field after a release is live. This will help reduce validator disruption and the burden of support over the longer term.

## Proposal

```[tasklist]
### Tasks
- [ ] Identify/prioritise the platforms we want to support based on validator feedback.
- [ ] https://github.com/cosmos/gaia/issues/2441
- [ ] Update release checklists, to incorporate information for platform support for all future releases.
- [ ] Include platform support requirement questions in future validator surveys to identify any future trends or needs.
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
Check out https://github.com/mvdan/github-actions-golang/blob/master/README.md

**Comment by mpoke** [comment]
Closing as not needed
