### ISSUE TITLE
Plan: Global Fee module refactor

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2270]
# Problem
The Global Fee module has been subject to much refactoring work recently. This issue brings together all the separated tasks and tracks down their respective status.

# Closing criteria
The Global fee module AnteHandler should be simplified (see #2228) and enables transaction messages to bypass fee charges based on parameters established through governance proposals (see #2213).

# Task list

```[tasklist]
### Fee AnteHandler
- [x] https://github.com/cosmos/gaia/issues/2351 #2327
- [x] https://github.com/cosmos/gaia/issues/2383 #2447
```
```[tasklist]
### Bypass messages
- [x] https://github.com/cosmos/gaia/issues/2366 #2424 #2352
- [x] https://github.com/cosmos/gaia/issues/2368 #2352
```
```[tasklist]
### Code improvements (backported to v9)
- [x] https://github.com/cosmos/gaia/issues/2321 #2316 - introduce changes from the [SDK team review](https://hackmd.io/ro5nWA4QRX2_0WRaGZJkqg)
- [x] https://github.com/cosmos/gaia/issues/2087  #2092
- [x] https://github.com/cosmos/gaia/issues/2213  #2218 
```

```[tasklist]
### Test
- [x] https://github.com/cosmos/gaia/issues/2456 [test scripts](https://gist.github.com/sainoe/9d4b6995b900ffdc052dfdb3d4df5ff3)
- [x] https://github.com/cosmos/gaia/issues/2457 part of  https://github.com/cosmos/gaia/pull/2352
- [x] https://github.com/cosmos/gaia/issues/2486 https://github.com/cosmos/gaia/pull/2532
```

```[tasklist]
### Docs
- [ ] https://github.com/cosmos/gaia/issues/2330 https://github.com/cosmos/gaia/pull/2463
- [ ] https://github.com/cosmos/gaia/issues/2485
```
```[tasklist]
### other issues
- [ ] https://github.com/cosmos/gaia/issues/2489
```

**Comment by mpoke** [comment]
Closing as the only task remaining is the ADR which is in review.
