### ISSUE TITLE
EPIC: Refactor Release Process

### ISSUE THREAD

**Issue by glnro** [cosmos/gaia#2355]
# Problem

The current Gaia release process is not sufficiently documented to facilitate current onboarding. Even with automation implemented like [goreleaser](https://github.com/cosmos/gaia/blob/main/.goreleaser.yml) for release generation, there are still manual processes and conventions that are not documented in [`RELEASING.md`](https://github.com/cosmos/gaia/blob/main/RELEASING.md) or anywhere else for that matter. 

# Closing criteria

Ensure documentation of every step of the release process:
  - Creating a new release branch and updating mergify configuration
  - Backporting features/fixes for releases (major & minor)
  - Changelog generation
  - Release Tagging
    - RC
    - Minor Release
    - Major Upgrade
  - Publishing
  - Notifying Communication Channels

# Problem details

The release process is currently fragmented; even the automated workflows could be refactored. In addition to lacking documentation, changelog generation, release notes generation, and release communication could benefit from better automation either through the use of new tools or leveraging existing configurations.

# Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/gaia/issues/2357
- [ ] https://github.com/cosmos/gaia/issues/2544
- [ ] https://github.com/cosmos/gaia/issues/2604
- [ ] https://github.com/cosmos/gaia/issues/2371
- [ ] https://github.com/cosmos/gaia/issues/2397
```

```[tasklist]
### Nice to have
- [ ] Spike on configuring socials or a bot for release notification for go-releaser
- [x] Create `UPGRADING.md` in release/v* with info for upgrading to the new version
- [ ] https://github.com/cosmos/gaia/issues/2401
```

Currently there is a [WIP](https://github.com/cosmos/gaia/pull/2290) for updates to `RELEASING.md`
