### ISSUE TITLE
Gaia v11.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2407]
# Problem

This is a meta issue used to track the release of Gaia v11. 

# Closing criteria

Gaia v11.0.0-rc0 is cut. 

# Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/gaia/issues/2270
- [ ] https://github.com/cosmos/gaia/issues/2588
- [ ] https://github.com/cosmos/gaia/issues/2353
- [ ] https://github.com/cosmos/gaia/issues/2084
- [ ] https://github.com/cosmos/gaia/issues/2593
```

```[tasklist]
### Nice to have
```
