### ISSUE TITLE
Gaia v10.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2497]
# Problem

This is a meta issue used to track the release of Gaia v10.

# Closing criteria

Gaia v10.0.0-rc0 is cut.

# Task list

```[tasklist]
### Must have
- [x] create `release/v10.0.x` branch from `release/v9.1.x`
- [ ] https://github.com/cosmos/gaia/issues/2280
- [ ] https://github.com/cosmos/gaia/issues/2282
- [x] bump SDK to 0.45.16-ics https://github.com/cosmos/gaia/pull/2488
- [x] Bump IBC to v4.4.0
- [x] cut v10.0.0-rc0 release with binaries
```

```[tasklist]
### Nice to have

```

**Comment by shaspitz** [comment]
GH actions bot is taking a while, but tag is cut https://github.com/cosmos/gaia/releases/tag/v10.0.0-rc0

**Comment by shaspitz** [comment]
See https://github.com/cosmos/gaia/compare/v9.1.0...v10.0.0-rc0
