### ISSUE TITLE
EPIC: Upgrade to v10 

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2530]
## Cosmos Hub Upgrade Epic

# v10

**Create an issue for each item** and mark complete once it has been done.

```[tasklist]
### Communication (during entire lifecycle)
- [ ] ~~Testnet blog post - target validators on Cosmos Medium~~
- [ ] ~~Tweet link to testnet upgrade blog - @ cosmohub~~
- [x] Testnet upgrade info (discord only)
- [x] Tweet updates on proposal status - @ cosmohub, [link](https://twitter.com/cosmoshub/status/1665643006924390400?s=46)
- [x] Mainnet blog post - target wider audience on Cosmos Medium, [link](https://docs.google.com/document/d/1OFTlbM5HxrUSfgRLdVeWnB4IpxHEhQi2CzQSUw9m05o/edit#) [blog](https://medium.com/the-interchain-foundation/cosmos-hubs-v10-upgrade-is-coming-59b1a7c6316)
- [x] Tweet link to mainnet upgrade blog - @ cosmos @ cosmoshub
- [x] Link to mainnet upgrade instructions (all channels - Discord, Telegram, Slack)
- [x] Tweet upgrade countdown during voting period - @ cosmos @ cosmoshub
- [x] Tweet upgrade success story - @ cosmos @ cosmoshub
```

```[tasklist]
### Library dependencies
- [x]  Upgrade to SDK version v0.45.16-ics
- [x]  Upgrade to IBC version v4.4
- [x] Upgrade to CometBFT version v0.34.28
```

```[tasklist]
### Testnet
- [x] Communication prep
- [x] Docs: [testnets](https://github.com/cosmos/testnets) updated with most recent rc
- [x] Docs: [join-testnet](https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/join-testnet.md)
- [x] Release candidate
- [x] Create testnet proposal
- [x] Final Release
```

```[tasklist]
### Docs
- [x] Quickstart in `docs/getting-started/quickstart.md` https://github.com/cosmos/gaia/pull/2599
- [x] Join mainnet in `docs/hub-tutorials/join-mainnet.md` https://github.com/cosmos/gaia/pull/2599
- [x] Migration docs in `docs/migration/` https://github.com/cosmos/gaia/pull/2599
- [x] Update `CHANGELOG.md`
- [x] Post Upgrade: [chain-registry.json](https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json) https://github.com/cosmos/chain-registry/pull/2250
- [ ] Post Upgrade: Update [cosmos mainnet repo](https://github.com/cosmos/mainnet) https://github.com/cosmos/mainnet/pull/170
```

```[tasklist]
### Mainnet Proposal
- [x] Predict block height for target date
- [x] Create forum post
- [x] Submit [on-chain proposal](https://www.mintscan.io/cosmos/proposals/798) 
```

```[tasklist]
### Followup release
- [x] [v10.0.1](https://github.com/cosmos/gaia/releases/tag/v10.0.1) patched release for Huckleberry
- [ ] ~~v10.0.2 update with [IBC Go v4.4.2](https://github.com/cosmos/ibc-go/releases/tag/v4.4.2)https://github.com/cosmos/gaia/issues/2561~~ Postponed till wk26
```
