### ISSUE TITLE
Refactor E2E Tests for SDK v0.47 & IBC v7

### ISSUE THREAD

**Issue by glnro** [cosmos/gaia#2536]
# Problem

Refactor existing base e2e tests and add new test cases for updated APIs.

## Background
In order to accommodate the upgrade to SDK v0.47 and IBC v7, a [minimal PR was opened](https://github.com/cosmos/gaia/pull/2541) to upgrade Gaia so that only unit and liveness tests would pass. All E2E tests were left commented out, to be reintroduced and/or refactored to be consistent with the new libraries and corresponding API's. 

# Closing criteria

- All E2E tests refactored and passing
- E2E user journeys documented
- New tests covering additional user journeys introduced in SDK v0.46 and v0.47.

# Problem details

**Gaia's E2E test suites exist to ensure safety against regressions for critical user journeys.** 

The following user journeys will remain consistent from SDK v0.45 to v0.47 and are categorized by executing module. These tests are currently commented out in the base branch and may need to be refactored.

**Existing Test Suites**
- Endpoint Regression
	- `testRestInterfaces` - Ensure node and module REST endpoints have been configured and return a 200.
- Bank
	- `testBankTokenTransfer` - Send tokens from account A to account B on the same chain
- BypassMinFee
	- `testBypassMinFeeWithdrawReward` - Submit a gov param change proposal to change the  bypass-min-fee message to include `MsgWithdrawDelegatorReward` and test succcess and failure cases with different fee amounts.
- Encode/Decode
	- `testEncode` - Encode transaction from json to base64
	- `testDecode`- Decode a transaction from base64 to json
- Evidence
	- `testEvidence` - Verify the expected volume of evidence generated in test setup persists and is is queryable
- FeeGrant
	- `testFeeGrant` - Execute a fee grant so that account 1 will pay fees for account 2 on chain A. Verify that expected fees are deducted.
- GlobalFee
	- `testGlobalFees` - Validate expected global fee configuration again test case matrix
	- `testQueryGlobalFeesInGenesis` - Validate globalfee initialized in genesis
- IBC
	- `testIBCTokenTransfer` - Send tokens from account A on chain 1 to account A on chain B
	- `testMultihopIBCTokenTransfer` (PFM) - Send tokens using packet-forward-middleware from account A on chain 1 through account A on chain 2 to account B on chain 1. Verify tokens successfully received.
	- `testFailedMultihopIBCTokenTransfer` (PFM) - Send tokens from account A on chain 1 through a nonviable address on chain 2. Verify transaction fails and tokens are returned to sender.
	- `testIBCBypassMsg` - Test fee bypassing for IBC messages:  `MsgRecvPacket`, `MsgAcknowledgement`, `MsgAcknowledgement`, and  `MsgUpdateClient` 
- Slashing
	- `testSlashing` - Successfully unjail validator previously jailed in test setup.
- Staking & Distribution
	- `testStaking` - Successfully delegate and redelegate tokens to a validator.
	- `testDistribution` - Successfully set new withdrawal address and withdraw rewards to it.
- Vesting
	- `testDelayedVestingAccount` - Verify token transfers fail until after end time.
	- `testContinuousVestingAccount` - Verify token transfer succeeds with expected amount after start time. 

**Refactor**
- Gov
	- `GovSoftwareUpgrade` -> `LegacySoftwareUpgrade` - Execute a software upgrade proposal and verify chain halts at expected height.
	- `GovCancelSoftwareUpgrade` - `LegacyCancelSoftwareUpgrade` - Execute a software upgrade proposal and subsequent cancel upgrade proposal. Verify chain does not halt at original proposal's halt-height.
	- `GovCommunityPoolSpend` - Deprecate
	- `AddRemoveConsumerChain` - Execute an add consumer chain proposal, and subsequent remove consumer chain proposal. 

**New Tests**
- Gov
	- `testSubmitBankSendProposal` - Execute a gov proposal with the new gov API that executes a bank send to an address from the gov module account,
	- `testSubmitSoftwareUpgrade` - Execute a software upgrade proposal with the new gov API
	- `testCancelSoftwareUpgrade` - Execute a cancel software upgrade proposal with the new gov API
- Bank
	- `testMultiSend` - Execute a bank multisend

# Task list

```[tasklist]
### QA
- [ ] Document user journeys and corresponding tests
```

```[tasklist]
### Update existing test suites to pass against the v47 feature branch
- [x] https://github.com/cosmos/gaia/issues/2622 https://github.com/cosmos/gaia/pull/2587
- [x] TestRestInterfaces
- [x] TestBank
- [x] TestEncode
- [x] TestEvidence
- [x] TestFeeGrant
- [x] TestGov
- [x] TestIBC
- [x] TestSlashing
- [x] TestStakingAndDistribution
- [x] TestVesting
- [x] https://github.com/cosmos/gaia/issues/2623
- [x] TestByPassMinFee
- [x] TestGlobalFees
- [x] TestAddConsumer
- [x] TestRemoveConsumer
```

```[tasklist]
### Add additional tests for API changes
- [x] Bank - Multisend
- [x] Gov - New proposal type with `MsgCommunityPoolSpend` msg exec.
- [x] Staking - Cancel unbonding operations
```

```[tasklist]
### Nice to have
- [ ] ~Ensure each test suite has benchmark comments for expected test setup and assertions.~
- [ ] ~Gov gated ICA test. ~See [v46 implementation](https://github.com/cosmos/gaia/blob/target-v0-46/tests/e2e/e2e_gov_test.go#L164) for details.~ superseded by #1746~
```
