### ISSUE TITLE
EPIC: Refactor to SDK v0.47 and IBC v7

### ISSUE THREAD

**Issue by glnro** [cosmos/gaia#2540]
#### Background
As of September 2022, Gaia was prepared to upgrade to SDK v0.46 and IBC v5. In order to accomodate  Interchain-Security (ICS) which had been built on v0.45 of the SDK, the work to update Gaia was reverted, and the application subsequently downgraded to SDK v0.45 and IBC v3. As SDK v0.45 is only being maintained for security patches and IBC v4 will be EOL by August 2023, is it imperative that Gaia upgrade to the latest stable SDK and IBC versions. 

#### Major Dependencies
In addition to the SDK and IBC, several other major dependencies include CometBFT, ICS,  and Packet-Forward-Middleware (PFM). While Comet has a major compatible version released, the remaining dependencies have yet to cut a major release with SDK v0.47, IBC v7, and Comet v0.37. At the time of writing, ICS and PFM dependencies are leveraging commits from a feature branch and main respectively. 

#### Internal Module Dependencies
The only proprietary module that Gaia has is `x/globalfee`. This module will also need to be updated to be compatible with SDK v0.47. 

#### Testing
In addition to ensuring existing unit, sim and e2e tests are functioning, additional test cases will need to be written to ensure regressions have not been introduced. For e2e this will include additional tests for the new gov api. For app wiring, this should at minimum include guarantees for partial ordering of modules (ie where the staking module needs to come before the provider module), that expected keepers are instantiated. 

### Target Branch
The canonical feature branch for this work is [feat/sdk-47-ibc-7](https://github.com/cosmos/gaia/tree/feat/sdk-47-ibc-7)

### Epics

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/gaia/issues/2533
- [ ] https://github.com/cosmos/gaia/issues/2534
- [ ] https://github.com/cosmos/gaia/issues/2535
- [ ] https://github.com/cosmos/gaia/issues/2536
- [ ] https://github.com/cosmos/gaia/issues/2537
- [ ] https://github.com/cosmos/gaia/issues/2574
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/gaia/issues/2538
```
