### ISSUE TITLE
Incoming user issues Q-3.23

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2617]
## Problem

This is a meta issue used to track incoming user issues addressed in Q3 2023

## Closing criteria

The completion of Q3 2023.

## User issues

```[tasklist]
### Issues
- [ ] https://github.com/cosmos/gaia/issues/2476
- [ ] https://github.com/cosmos/gaia/issues/2478
- [ ] https://github.com/cosmos/gaia/issues/2482
- [ ] https://github.com/cosmos/gaia/issues/2347
- [ ] https://github.com/cosmos/gaia/issues/1958
- [ ] https://github.com/cosmos/gaia/issues/2313
- [ ] https://github.com/cosmos/gaia/issues/2483
- [ ] https://github.com/cosmos/gaia/issues/2415
- [ ] https://github.com/cosmos/gaia/issues/2358
- [ ] https://github.com/cosmos/gaia/issues/2658
- [ ] https://github.com/cosmos/gaia/issues/2685
- [ ] https://github.com/cosmos/gaia/issues/2689
- [ ] https://github.com/cosmos/gaia/issues/2694
- [ ] https://github.com/cosmos/gaia/issues/2693
```
