### ISSUE TITLE
Gaia v12.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2649]
## Problem

This is a meta issue used to track the release of Gaia v12 with LSM enabled.

## Closing criteria

Gaia v12.0.0-rc0 is cut.

## Task list

```[tasklist]
### Must have
- [x] integrate LSM https://github.com/cosmos/cosmos-sdk/pull/16747
- [ ] https://github.com/cosmos/gaia/issues/2682
- [x] add necessary migration code to the upgrade handler
- [x] add e2e tests to check LSM https://github.com/cosmos/gaia/pull/2679
- [x] update Gaia docs to include LSM changes https://github.com/cosmos/gaia/pull/2683
- [x] replace RCs with final release (SDK, ICS, Gaia)
```

```[tasklist]
### Nice to have

```

**Comment by riley-stride** [comment]
- Cosmos-sdk docs: https://github.com/cosmos/cosmos-sdk/pull/17281
- Gaia docs: https://github.com/cosmos/gaia/pull/2683
