### ISSUE TITLE
EPIC: Cosmos Hub Upgrade to Gaia v11.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2673]
## Cosmos Hub Upgrade to Gaia v11.0.0

```[tasklist]
### After Cutting Release Candidate
- [x] Coordinate with Hypha to test release candidate
- [x] Create proposal text draft
- [x] Post proposal text draft on forum
- [x] Upgrade release and replicated security testnets (note: on Wednesdays)
- [x] Review post-upgrade status of affected features if necessary
```

```[tasklist]
### Before Proposal Submission (TODO sync on a call)
- [x] Cut final release
- [x] Predict block height for target date (16596000)
- [x] Update/proofread proposal text
- [x] Transfer deposit amount (i.e., 250 ATOMs) to submitter wallet
- [x] Create upgrade docs (with disclaimer upgrade prop still being voted on)
- [x] Coordinate with marketing/comms to prep communication channels/posts
```

```[tasklist]
### Voting Period
- [x] Estimate threshold of validators that are aware of proposal and have voted or confirmed their vote
- [x] Coordinate with marketing/comms to update on voting progress (and any change in upgrade time)
```

```[tasklist]
## Proposal Passed
- [x] Determine "on-call" team: available on Discord in [#cosmos-hub-validators-verified](https://discord.com/channels/669268347736686612/798937713474142229) during upgrade
- [x] Coordinate with marketing/comms on who will be available, increase regular upgrade time updates and validator outreach
- [x] Prep Gaia docs: `docs/getting-started/quickstart.md`, `docs/hub-tutorials/join-mainnet.md`, `docs/migration/` (open PR)
- [x] Update [Chain Registry](https://github.com/cosmos/chain-registry/pull/2576) - PR in place
- [x] Prep [cosmos mainnet repo](https://github.com/cosmos/mainnet) update (open PR)
- [x] Prep internal statesync node for upgrade (confirm cosmovisor configured)
- [x] Reach out to main dependency teams -- Comet, IBC, SDK -- for assistance during the upgrade (#gaia-release-warroom on Slack)
```

```[tasklist]
## During Upgrade (note: on Wednesdays at 15:00 UTC)
- [x] Available on Discord in [#cosmos-hub-validators-verified](https://discord.com/channels/669268347736686612/798937713474142229)
- [x] Available on Twitter / Slack / Telegram
```

```[tasklist]
## Post Upgrade
- [x] Merge PRs for Gaia docs & chain-registry update
- [x] FAQ: collect issues on upgrade from discord
- [x] Hold validator feedback session
```
