### ISSUE TITLE
Gaia v14 Software Upgrade Checklist

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#2786]
## Cosmos Hub Upgrade to Gaia <Version>

```[tasklist]
### After Cutting Release Candidate
- [x] Coordinate with Hypha to test release candidate **[Marius, Hypha]**
- [x] Create proposal text draft **[Milan, Brian, Hypha]**
- [x] Post proposal text draft on forum **[Milan, Hypha]**
- [x] Upgrade release and replicated security testnets (note: on Wednesdays) **[Hypha]**
- [x] Review proposal feedback of affected features if necessary **[Milan, Brian, Jehan, Marius]**
- [x] Discuss crypto equivocation feature review from AiB [Simon]
```

```[tasklist]
### Before Proposal Submission (TODO sync on a call)
- [x] Cut final release **[Marius]**
- [x] Predict block height for target date **[Hypha]**
- [x] Update/proofread proposal text **[Brian, Marius, Hypha]**
- [x] Transfer deposit amount (i.e., 250 ATOMs) to submitter wallet **[Milan, Jehan]**
- [x] Create upgrade docs (with disclaimer upgrade prop still being voted on) **[Milan]**
- [x] Coordinate with marketing/comms to prep communication channels/posts **[Milan, Brian]**
```

```[tasklist]
### Voting Period
- [x] Estimate threshold of validators that are aware of proposal and have voted or confirmed their vote **[Milan, Brian]**
- [x] Coordinate with marketing/comms to update on voting progress (and any change in upgrade time) **[Milan, Brian, Syed, Rob]**
```

```[tasklist]
## Proposal Passed
- [x] Determine "on-call" team: available on Discord in [#cosmos-hub-validators-verified](https://discord.com/channels/669268347736686612/798937713474142229) during upgrade **[Marius]**
- [x] Coordinate with marketing/comms on who will be available, increase regular upgrade time updates and validator outreach **[Milan, Brian]**
- [x] Prep Gaia docs: `docs/getting-started/quickstart.md`, `docs/hub-tutorials/join-mainnet.md`, `docs/migration/` https://github.com/cosmos/gaia/pull/2839 **[Milan]**
- [x] Prep chain-registry update: https://github.com/cosmos/chain-registry/pull/3375 **[Milan]**
- [x] Prep cosmos mainnet repo update: https://github.com/cosmos/mainnet/pull/175 **[Milan]**
- [ ] Prep internal statesync node for upgrade (confirm cosmovisor configured) **[Matija]**
- [ ] Reach out to main dependency teams -- Comet, IBC, SDK -- for assistance during the upgrade (#gaia-release-warroom on Slack) **[Marius]**
- [x] Add Cryptographic Eq. docs to Gaia (Validator concerns) https://github.com/cosmos/gaia/pull/2854 **[Milan]**
- [x] Add Cryptographic Eq. docs to ICS repo (technical overview)
```

```[tasklist]
## During Upgrade (note: on Wednesdays at 15:00 UTC)
- [x] Available on Discord in [#cosmos-hub-validators-verified](https://discord.com/channels/669268347736686612/798937713474142229) **[Marius]**
- [x] Available on Twitter / Slack / Telegram  **[Marius]**
- [x] Create new Upgrade Log and monitor upgrade status on [PingPub](https://ping.pub/cosmos/uptime) **[Milan]**
```

```[tasklist]
## Post Upgrade
- [x] Merge PRs for Gaia docs & chain-registry update **[Milan]**
- [x] FAQ: collect issues on upgrade from discord **[Milan]**
- [ ] Hold validator feedback session **[Milan, Brian]**
```
