### ISSUE TITLE
EPIC: Update validator content in Gaia docs

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2867]
## Problem

The docs relevant to validators might be outdated or difficult to consume. In order to improve the UX for validators, we need to update the content. 

## Closing criteria

The validator content in Gaia docs is updated

## Task list

```[tasklist]
### Must have
- [x] **Prerequisite:** move docs platform to docusaurus
- [x] Add versioning to docs platform (see SDK)
- [ ] Review existing validator content and create plan for updating it
- [ ] Update the content
```

```[tasklist]
### Nice to have

```
