### ISSUE TITLE
Enable ICA controller

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2869]
## Summary

With the [Gaia upgrade to SDK 0.47 and IBC 7](https://github.com/cosmos/gaia/issues/2790), we can enable the ICA controller  on the Cosmos Hub. 

## Problem Definition

The ICA controller would enable the Hub to control accounts on remote chains. An example of an application is the provider-based governance that would allow the governance of a consumer chain to be control by ATOM stakers. See the [IBC docs](https://ibc.cosmos.network/main/apps/interchain-accounts/overview.html) for more details. 

## Proposal

A prerequisite is upgrading the Hub to IBC 7, which will happen with the v15 upgrade. 

## Task list

```[tasklist]
### Must have
- [ ] align with stakeholders on potential use cases (e.g., Neutron)
- [ ] https://github.com/cosmos/gaia/issues/2539
- [ ] https://github.com/cosmos/gaia/issues/2979
```

```[tasklist]
### Nice to have
```
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Pre-requisite was achieved with https://github.com/cosmos/gaia/releases/tag/v15.0.0.

When tackling this issue, we should split it into smaller steps:
1. enable the basic ICA controller
2. connect ICA to governance (allow the Hub governance to control accounts on other chains)
