### ISSUE TITLE
Adopt the Skip Block SDK & x/feemarket (EIP-1559)

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2870]
## Summary

Adopt the Skip Block SDK and include the EIP-1559 fee market lane. 

## Problem Definition

The current fee market on the Cosmos Hub is very rudimentary and overdue for an upgrade. Transactions are charged a minimum fee irregardless of network load or demand, which is set by governance. Individual validators may choose to responsively increase fees by changing their local configuration. See [gov proposal 842](https://www.mintscan.io/cosmos/proposals/842) for more details. 

## Proposal

After the Cosmos Hub upgrades to Cosmos SDK 0.47 and has proven the software is stable, the subsequent upgrade should adopt the open-source Block SDK, the primary research and development focus of Skip Protocol built on ABCI++, and include the EIP-1559 fee market lane that Skip is building in collaboration with Osmosis Labs. (cf. [gov proposal 842](https://www.mintscan.io/cosmos/proposals/842)). 

## Task list

```[tasklist]
### Must have
- [x] align with Skip on integration docs
- [ ] integrate Block SDK
- [x] include the EIP-1559 [fee market lane](https://github.com/skip-mev/feemarket/blob/main/x/feemarket/)
- [x] add necessary tests (e2e/integration)
```

```[tasklist]
### Nice to have
```
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
Relevant resources (thanks to [Skip Protocol](https://twitter.com/SkipProtocol)):

- docs on block-sdk and how to integrate it https://docs.skip.money/chains/overview/
- block-sdk testapp docs https://github.com/skip-mev/block-sdk/tree/main/tests/app
- block-sdk repo https://github.com/skip-mev/block-sdk/tree/main
- EIP-1559 implementation repo https://github.com/skip-mev/feemarket/tree/main

**Comment by mpoke** [comment]
This is closed by the v18.0.0 release
