### ISSUE TITLE
Improve usability/documentation of Gaia e2e tests

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/gaia#2902]
## Problem

We want to improve the usability of the Gaia e2e tests. This concerns mostly the documentation around the e2e tests, but if there are easy things we can change/refactor/add to improve the tests, we should be aware of those and consider doing them, too.

## Closing criteria

We have more confidence in the Gaia e2e tests,
and it is easier to onboard onto them.

## Problem details

The problems we seem to have with the Gaia e2e tests currently are:
1) it is not easy to find out what is being tested or not
2) it is hard to onboard onto the e2e tests
3) some things are tested by Hypha very late in the process (e.g. upgrades),
even though it might be possible to test them earlier and fail sooner rather than later. 

## Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/gaia/issues/2903
```

```[tasklist]
### Nice to have
* [ ] Create an overview of test scenarios that are being done in the Gaia e2e tests
* [ ] Incorporate parts of Hyphas test suite in Gaia, e.g. more/better upgrade tests
```

**Comment by mpoke** [comment]
Closing this in favor of https://github.com/cosmos/gaia/issues/2903
