### ISSUE TITLE
Use ICS@v3.3.x-lsm

### ISSUE THREAD

**Issue by MSalopek** [cosmos/gaia#2916]
```[tasklist]
### Tasks
- [x] add v47-lsm changes to release/v3.3.x -> https://github.com/cosmos/interchain-security/pull/1617
- [x] create a release ICS v3.3.1-lsm
- [x] use release ICS v3.3.1.-lsm on gaia
```
