### ISSUE TITLE
 Enable IBC fee middleware

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2948]
## Summary

Enable IBC fee middleware (see [IBC docs](https://ibc.cosmos.network/main/middleware/ics29-fee/overview)). 

## Problem Definition

The IBC fee middleware will enable the creation of new channels with incentivize relaying. Furthermore, once we upgrade to IBC 8.1, we can upgrade existing channels. 

## Task list

```[tasklist]
### Must have
- [x] enable the fee middleware module
- [ ] update documentation
- [ ] add integration or e2e tests
```

```[tasklist]
### Nice to have
```
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?
