### ISSUE TITLE
[Epic]: Gaia v21.0.0

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#3353]
## Problem

This is a meta issue used to track the release of Gaia v21.

## Closing criteria

Gaia v21.0.0-rc0 is cut.

## Task list

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/gaia/issues/3365
- [x] Bump ICS to latest version to fix ICS reward distribution https://github.com/cosmos/interchain-security/issues/2286
- [x] Add needed migration for ICS reward distribution https://github.com/cosmos/gaia/pull/3361
- [ ] https://github.com/cosmos/gaia/issues/3373
- [ ] https://github.com/cosmos/gaia/issues/3372
```

```[tasklist]
### Nice to have
```
