### ISSUE TITLE
[Epic]: Gaia v22

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#3386]
## Problem

This is a meta issue used to track the release of Gaia v22.

## Closing criteria

Gaia v22.0.0-rc0 is cut.

## Task list

```[tasklist]
### Must have
- [ ] bump ICS to v6.4.0 -- https://github.com/cosmos/interchain-security/issues/2382
- [ ] update chain-registry to reference gaiad v22 as cannonical
- [x] Bump SDK to include latest changes
- [x] update to latest version of wasmd https://github.com/cosmos/gaia/pull/3459
```

```[tasklist]
### Nice to have
- [x] Bump SDK to 0.50.10-lsm https://github.com/cosmos/gaia/pull/3370
```
