### ISSUE TITLE
ci: tracking issue

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/gaia#404]
## Summary

This issue is meant as a tracking issue for changes to CI. 

From a conversatioin with @jackzampolin we concluded:

- [ ] Have each commit build a docker image and push it to a docker registry
- [ ] Automate release pipeline
  - [ ] pushinig a tag creates a release
     - [ ] creates binaries (gaiad, gaiacli)
     - [ ] reproducible builds and hashes to be added to the release body. 
     - [ ] push tag/release docker images
     - [ ] push `:latest` Docker image tag for newest version

If there are more asks please comment below.

**Comment by alexanderbez** [comment]
> Have each commit build a docker image and push it to a docker registry

Each commit or each tag/release?

**Comment by tac0turtle** [comment]
each commit was asked for ({docker_org}/gaia-{branch_name}). tag and release images would be plain {docker_org}/gaia

**Comment by alexanderbez** [comment]
Ohh I see. A single docker image for each branch that is updated after each commit?

**Comment by tac0turtle** [comment]
Yea

**Comment by tac0turtle** [comment]
@alexanderbez do we want the pushing of docker images on every branch for sdk as well? This could be useful if we want to spin up short-lived testnets for major changes and/or benchmark testing.

P.S. I don't think this is a proposal

**Comment by alexanderbez** [comment]
I imagine we'd only do that for release candidates and other similar tags/branches. If we go with having an image pushed for every branch, wouldn't we have many images in the docker repo that are never purged?

**Comment by tac0turtle** [comment]
yes there would be many images, but we could do weekly purges. There are multiple ways to go about this, I think every branch is just one. (I don't fully understand the need for every branch, but it was a request)

Also since ci and docker hub are pratically free then this shouldn't be a worry.

**Comment by alexanderbez** [comment]
Can you do automatic purges? I would say go with what you think is needed and most beneficial.

**Comment by tac0turtle** [comment]
`curl -X DELETE -u "$user:$pass" https://index.docker.io/v1/repositories/$namespace/$reponame/`
shold be able to set it up to delete when pushed to master, if not then every couple of days

**Comment by tac0turtle** [comment]
won't be able to provide binaries as goreleaser does not work with cgo currently. Also, we need to figure out how we would like reproducible builds to work as right now they hashes aren't being outputted anywhere.
