### ISSUE TITLE
[Hub] cosmoshub-4.6 tracking

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#713]
The branch `cosmoshub-4.6` is going to be used for the upcoming upgrade.

The current soft target for the cosmos hub upgrade is June, 2021.

- [ ] latest version of sdk, at alpha
- [ ] latest version of tendermint, awaiting v0.35 rc
- [ ] latest version of ibc-go, at alpha
- [ ] latest version of dex, to be imported after updating to sdk alpha
- [ ] documentation
  - [ ] upgrade
  - [ ] breaking changes
  - [ ] cosmovisor
  - [ ] ibc
- [ ] governance
  - [ ] cip
  - [ ] dex parameter change proposal
  - [ ] ibc upgrade proposal
- [ ] upgrade policies, e.g., cosmosvisor
  - [ ] cip?

**Comment by shahankhatch** [comment]
The branch `hub/cosmoshub-5` is the target.

**Comment by shahankhatch** [comment]
Renaming this to become a cosmoshub-5 tracking issue.

**Comment by shahankhatch** [comment]
The cosmoshub-5 chain id won't be used, so I'm going to delete the branch (there were no new commits into it).

I created an interim branch `cosmoshub-4.6` that is importing available alpha releases.

I'm going to update this issue to track the upcoming upgrade.

**Comment by shahankhatch** [comment]
Yes, please and thanks @hxrts. Wdyt of titling it something like `cosmoshub upgrades`?

**Comment by hxrts** [comment]
> Yes, please and thanks @hxrts. Wdyt of titling it something like `cosmoshub upgrades`?

Up to you. If you'd prefer to have a catch-all channel for upgrades vs a chan for specific upgrades that works for me. I could see concurrent conversations on n and n+1 upgrades potentially being helpful in certain scenarios. Could be more trouble than it's worth though.
